
#constants

SERVICE_SHELVER = "SERVICE_SHELVER"
SERVICE_NETWORK = "SERVICE_NETWORK"
SERVICE_INTERNAL = "SERVICE_INTERNAL"
SERVICE_NODE = "SERVICE_NODE"
SERVICE_ECHO = "SERVICE_ECHO"
SERVICE_DATABASE = "SERVICE_DATABASE"
SERVICE_TOPOLOGY = "SERVICE_TOPOLOGY"


NETWORK_TERMINATE = "NETWORK_TERMINATE"
NETWORK_PEER_CONNECT = "NETWORK_PEER_CONNECT"
NETWORK_PEER_DISCONNECT = "NETWORK_PEER_DISCONNECT"
NETWORK_PEER_CONNECTED = "NETWORK_PEER_CONNECTED"
NETWORK_PEER_DISCONNECTED = "PEER_DISCONNECTED"
NETWORK_PEER_DATA_SENT = "NETWORK_PEER_DATA_SENT"
NETWORK_PEER_DATA_RECEIVED = "NETWORK_PEER_DATA_RECEIVED"



MESSAGE_START_SERVER = "START_SERVER"
MESSAGE_STOP_SERVER = "STOP_SERVER"
MESSAGE_SEND_PEER_DATA = "SEND_PEER_DATA"
MESSAGE_DISCONNECT_PEER = "DISCONNECT_PEER"

